topic_ontology = 'Topic categories: GYNECOLOGICAL HISTORY | MEDICATIONS | CHIEF COMPLAINTS | PAST MEDICAL HISTORY | ALLERGY | FAMILY AND SOCIAL HISTORY | PAST SURGICAL | OTHER_HISTORY | ASSESSMENT | REVIEW OF SYSTEM | DISPOSITION | EXAM | PLAN | DIAGNOSIS | ED COURSE | IMMUNIZATIONS | LABS | IMAGING | PROCEDURES | GYNHX'

topic_ontology_new = 'Topic categories: GENERAL HISTORY | MEDICATIONS | CHIEF COMPLAINTS | PAST MEDICAL HISTORY | ALLERGY | FAMILY AND SOCIAL HISTORY | PAST SURGICAL | OTHER_HISTORY | ASSESSMENT | REVIEW OF SYSTEM | DISPOSITION | EXAM | PLAN | DIAGNOSIS | ED COURSE | IMMUNIZATIONS | LABS | IMAGING | PROCEDURES | GYNECOLOGICAL HISTORY'
topic_ontology_canonical = 'Topic categories: CHIEF COMPLAINT | RESULTS | REVIEW OF SYSTEMS | HISTORY OF PRESENT ILLNESS | PHYSICAL EXAM | INSTRUCTIONS | ASSESSMENT AND PLAN | VITALS | MEDICATIONS | MEDICAL HISTORY | FAMILY AND SOCIAL HISTORY | SURGICAL HISTORY | ALLERGIES'
CANONICAL_CLASSES = ['CHIEF COMPLAINT',
                     'RESULTS',
                     'REVIEW OF SYSTEMS',
                     'HISTORY OF PRESENT ILLNESS',
                     'PHYSICAL EXAM',
                     'INSTRUCTIONS',
                     'ASSESSMENT AND PLAN',
                     'VITALS',
                     'MEDICATIONS',
                     'MEDICAL HISTORY',
                     'FAMILY AND SOCIAL HISTORY',
                     'SURGICAL HISTORY',
                      'ALLERGIES'


    
]
CLINICAL_T5_LARGE_MODEL_NAME = '/home/sitongz/UnifiedSKG/physionet.org/files/clinical-t5/1.0.0/Clinical-T5-Large'
CLINICAL_T5_SCRATCH_MODEL_NAME = '/home/sitongz/UnifiedSKG/physionet.org/files/clinical-t5/1.0.0/Clinical-T5-Scratch'
CLINICAL_T5_SCRATCH_MODEL_NAME_SAFE = 'download_models/Clinical-T5-Scratch'

CC= 'CC'
GENHX = 'GENHX'
FAM_SOCHX = 'FAM/SOCHX'

PASTMEDICALHX = 'PASTMEDICALHX'
ROS = 'ROS'
PASTSURGICAL = 'PASTSURGICAL'
MEDICATIONS = 'MEDICATIONS'
ALLERGY = 'ALLERGY'
ASSESSMENT = 'ASSESSMENT'
EXAM = 'EXAM'
DIAGNOSIS = 'DIAGNOSIS'
DISPOSITION = 'DISPOSITION'
PLAN = 'PLAN'
VITALS = 'VITALS'
FINDINGS = 'FINDINGS'
IMAGING = 'IMAGING'
PROCEDURES = 'PROCEDURES'
IMMUNIZATIONS = 'IMMUNIZATIONS'
LABS = 'LABS'
OTHER_HISTORY = 'OTHER_HISTORY'
GYNHX = 'GYNHX'
EDCOURSE = 'EDCOURSE'


section2full_old = {GENHX: 'General History',
 FAM_SOCHX: 'Family and Social History',
 PASTSURGICAL: 'past surgical',
 ROS: 'Review of System',
 ASSESSMENT: 'Assessment',
 PASTMEDICALHX: 'Past Medical History',
 MEDICATIONS: 'MEDICATIONS',
 GYNHX: 'gynecological history',
 CC: 'Chief Complaints',
 EDCOURSE: 'ED Course', 
               }

SECTION2FULL = {'GENHX': 'General History',
 'FAM/SOCHX': 'Family and Social History',
 'PASTSURGICAL': 'past surgical',
 'ROS': 'Review of System',
 'ASSESSMENT': 'Assessment',
 'PASTMEDICALHX': 'Past Medical History',
 'MEDICATIONS': 'MEDICATIONS',
 'GYNHX': 'gynecological history',
 'CC': 'Chief Complaints',
# 'EDCOURSE': ['emergency department course', 'ED Course'],
 'EDCOURSE': 'emergency department',
               }
FULL2SECTION = {v.lower():k for k,v in SECTION2FULL.items() }

SECTIONS = ['ALLERGY', 'ASSESSMENT', 'CHIEF_COMPLAINTS', 
            'DIAGNOSIS', 'DISPOSITION', 'EMERGENCY_DEPARTMENT',
              'EXAM', 'FAMILY_AND_SOCIAL_HISTORY',
                'GENERAL_HISTORY', 'GYNECOLOGICAL_HISTORY',
             'IMAGING', 'LABS', 'MEDICATIONS', 'OTHER_HISTORY',
               'PAST_MEDICAL_HISTORY', 'PAST_SURGICAL',
                 'PLAN', 'PROCEDURES', 'REVIEW_OF_SYSTEM','OTHER']
UNIMPORTANT_SECTIONS = [ 'GYNECOLOGICAL_HISTORY','EMERGENCY_DEPARTMENT','DISPOSITION','IMMUNIZATIONS','IMAGING','PROCEDURES','OTHER_HISTORY','LABS']
IMPORTANT_SECTIONS = [s for s in SECTIONS if s not in UNIMPORTANT_SECTIONS]
IMPORTANT_SECTION2BERT_ID = {IMPORTANT_SECTIONS[i]:i for i in range(len(IMPORTANT_SECTIONS))}
SECTION2BERT_ID = {SECTIONS[i]:i for i in range(len(SECTIONS))}

#----------------------------------------------------
# Subsection classification - Merge the Task A labels
#----------------------------------------------------
MERGE = {}
MERGE['AP'] = ['ASSSESSMENT', 'PLAN']

#--------------------------------------------
# Subsections for each first-level section
#--------------------------------------------
SUBJECTIVE = ['CC', 'HPI', 'ROS', 'PASTMEDICALHX', 'FAM/SOCHX', 'GENHX', \
              'PASTSURGICAL', 'ALLERGY', 'MEDICATIONS', 'DISPOSITION', \
              'ED COURSE', 'IMMUNIZATIONS', 'PROCEDURES', 'GYNECOLOGICAL HISTORY']
OBJECTIVE_EXAM = ['EXAM']
OBJECTIVE_RESULTS = ['DIAGNOSIS']
AP = ['AP']

#----------------------------------------------
# Collection of section and subsection headings
#----------------------------------------------
SECTIONS = {}
SECTIONS['SUBJECTIVE'] = SUBJECTIVE
SECTIONS['OBJECTIVE_EXAM'] = OBJECTIVE_EXAM
SECTIONS['OBJECTIVE_RESULTS'] = OBJECTIVE_RESULTS
SECTIONS['ASSSESSMENT'] = AP

#--------------------------------------------
# List of all subsections for classification,
# including, "OTHER", label
#--------------------------------------------
SUBSECTIONS = [subsection for section, subsections in SECTIONS.items() \
                 for subsection in subsections]
SUBSECTIONS.append('OTHER')

#--------------------------------------------------------
# Map between normalized section names and expanded forms
#--------------------------------------------------------
SUBSECTION_MAP = {}
SUBSECTION_MAP['CC'] = 'CHIEF COMPLAINT'
SUBSECTION_MAP['HPI'] = 'HISTORY OF PRESENT ILLNESS'
SUBSECTION_MAP['ROS'] = 'REVIEW OF SYSTEMS'
SUBSECTION_MAP['PASTMEDICALHX'] = 'PAST MEDICAL HISTORY'
SUBSECTION_MAP['FAM/SOCHX'] = 'FAMILY/SOCIAL HISTORY'
SUBSECTION_MAP['GENHX'] = 'GENERAL HISTORY'
SUBSECTION_MAP['PASTSURGICAL'] = 'SURGICAL HISTORY'
SUBSECTION_MAP['ALLERGY'] = 'ALLERGIES'
SUBSECTION_MAP['MEDICATIONS'] = 'CURRENT MEDICATIONS'
SUBSECTION_MAP['DISPOSITION'] = 'DISPOSITION'
SUBSECTION_MAP['ED COURSE'] = 'ED COURSE'
SUBSECTION_MAP['IMMUNIZATIONS'] = 'IMMUNIZATIONS'
SUBSECTION_MAP['PROCEDURES'] = 'PROCEDURES'
SUBSECTION_MAP['GYNECOLOGICAL HISTORY'] = 'GYNECOLOGICAL HISTORY'
SUBSECTION_MAP['EXAM'] = 'PHYSICAL EXAM'
SUBSECTION_MAP['DIAGNOSIS'] = 'DIAGNOSIS'
SUBSECTION_MAP['AP'] = 'ASSESSMENT AND PLAN'
SUBSECTION_MAP['ASSESSMENT'] = 'ASSESSMENT'
SUBSECTION_MAP['PLAN'] = 'PLAN'
SUBSECTION_MAP['VITALS'] = 'VITALS'
SUBSECTION_MAP['FINDINGS'] = 'FINDINGS'
SUBSECTION_MAP['OTHER'] = 'OTHER'

#--------------------------------------------------------
# Map between normalized section names and expanded forms
#--------------------------------------------------------
CLASSIFICATION_MAP = {}
CLASSIFICATION_MAP['CHIEF COMPLAINTS'] = 'CHIEF COMPLAINT'
CLASSIFICATION_MAP['GENERAL HISTORY'] = 'HISTORY OF PRESENT ILLNESS'
CLASSIFICATION_MAP['OTHER_HISTORY'] = 'HISTORY OF PRESENT ILLNESS'
CLASSIFICATION_MAP['REVIEW OF SYSTEM'] = 'REVIEW OF SYSTEMS'
CLASSIFICATION_MAP['PAST MEDICAL HISTORY'] = 'PAST MEDICAL HISTORY'
CLASSIFICATION_MAP['FAMILY AND SOCIAL HISTORY'] = 'FAMILY/SOCIAL HISTORY'
CLASSIFICATION_MAP['PAST SURGICAL'] = 'SURGICAL HISTORY'
CLASSIFICATION_MAP['ALLERGY'] = 'ALLERGIES'
CLASSIFICATION_MAP['MEDICATIONS'] = 'CURRENT MEDICATIONS'
CLASSIFICATION_MAP['DISPOSITION'] = 'DISPOSITION'
CLASSIFICATION_MAP['ED COURSE'] = 'ED COURSE'
CLASSIFICATION_MAP['IMMUNIZATIONS'] = 'IMMUNIZATIONS'
CLASSIFICATION_MAP['PROCEDURES'] = 'PROCEDURES'
CLASSIFICATION_MAP['GYNECOLOGICAL HISTORY'] = 'GYNECOLOGICAL HISTORY'
CLASSIFICATION_MAP['EXAM'] = 'PHYSICAL EXAM'
CLASSIFICATION_MAP['DIAGNOSIS'] = 'DIAGNOSIS'
CLASSIFICATION_MAP['LABS'] = 'FINDINGS'
CLASSIFICATION_MAP['IMAGING'] = 'FINDINGS'
CLASSIFICATION_MAP['ASSESSMENT'] = 'ASSESSMENT'
CLASSIFICATION_MAP['PLAN'] = 'PLAN'
CLASSIFICATION_MAP['OTHER'] = 'OTHER'