topic_ontology = 'Topic categories: GYNECOLOGICAL HISTORY | MEDICATIONS | CHIEF COMPLAINTS | PAST MEDICAL HISTORY | ALLERGY | FAMILY AND SOCIAL HISTORY | PAST SURGICAL | OTHER_HISTORY | ASSESSMENT | REVIEW OF SYSTEM | DISPOSITION | EXAM | PLAN | DIAGNOSIS | ED COURSE | IMMUNIZATIONS | LABS | IMAGING | PROCEDURES | GYNHX'


topic_ontology_new = 'Topic categories: GENERAL HISTORY | MEDICATIONS | CHIEF COMPLAINTS | PAST MEDICAL HISTORY | ALLERGY | FAMILY AND SOCIAL HISTORY | PAST SURGICAL | OTHER_HISTORY | ASSESSMENT | REVIEW OF SYSTEM | DISPOSITION | EXAM | PLAN | DIAGNOSIS | ED COURSE | IMMUNIZATIONS | LABS | IMAGING | PROCEDURES | GYNECOLOGICAL HISTORY'


topic_ontology_taskA_topic = 'Topic categories: GENERAL_HISTORY | MEDICATIONS | CHIEF_COMPLAINTS | PAST_MEDICAL_HISTORY | ALLERGY | FAMILY_AND_SOCIAL_HISTORY | PAST_SURGICAL | OTHER_HISTORY | ASSESSMENT | REVIEW_OF_SYSTEM | DISPOSITION | EXAM | PLAN | DIAGNOSIS | EMERGENCY_DEPARTMENT | IMMUNIZATIONS | LABS | IMAGING | PROCEDURES | GYNECOLOGICAL_HISTORY'

CLINICAL_T5_LARGE_MODEL_NAME = '/home/sitongz/UnifiedSKG/physionet.org/files/clinical-t5/1.0.0/Clinical-T5-Large'
CLINICAL_T5_SCRATCH_MODEL_NAME = '/home/sitongz/UnifiedSKG/physionet.org/files/clinical-t5/1.0.0/Clinical-T5-Scratch'
CLINICAL_T5_SCRATCH_MODEL_NAME_SAFE = 'download_models/Clinical-T5-Scratch'



CC= 'CC'
GENHX = 'GENHX'
FAM_SOCHX = 'FAM/SOCHX'

PASTMEDICALHX = 'PASTMEDICALHX'
ROS = 'ROS'
PASTSURGICAL = 'PASTSURGICAL'
MEDICATIONS = 'MEDICATIONS'
ALLERGY = 'ALLERGY'
ASSESSMENT = 'ASSESSMENT'
EXAM = 'EXAM'
DIAGNOSIS = 'DIAGNOSIS'
DISPOSITION = 'DISPOSITION'
PLAN = 'PLAN'
VITALS = 'VITALS'
FINDINGS = 'FINDINGS'
IMAGING = 'IMAGING'
PROCEDURES = 'PROCEDURES'
IMMUNIZATIONS = 'IMMUNIZATIONS'
LABS = 'LABS'
OTHER_HISTORY = 'OTHER_HISTORY'
GYNHX = 'GYNHX'
EDCOURSE = 'EDCOURSE'


section2full_old = {GENHX: 'General History',
 FAM_SOCHX: 'Family and Social History',
 PASTSURGICAL: 'past surgical',
 ROS: 'Review of System',
 ASSESSMENT: 'Assessment',
 PASTMEDICALHX: 'Past Medical History',
 MEDICATIONS: 'MEDICATIONS',
 GYNHX: 'gynecological history',
 CC: 'Chief Complaints',
 EDCOURSE: 'ED Course', 
               }

SECTION2FULL = {'GENHX': 'General History',
 'FAM/SOCHX': 'Family and Social History',
 'PASTSURGICAL': 'past surgical',
 'ROS': 'Review of System',
 'ASSESSMENT': 'Assessment',
 'PASTMEDICALHX': 'Past Medical History',
 'MEDICATIONS': 'MEDICATIONS',
 'GYNHX': 'gynecological history',
 'CC': 'Chief Complaints',
# 'EDCOURSE': ['emergency department course', 'ED Course'],
 'EDCOURSE': 'emergency department',
               }
FULL2SECTION = {v.lower():k for k,v in SECTION2FULL.items() }

SECTIONS = ['ALLERGY', 'ASSESSMENT', 'CHIEF_COMPLAINTS', 
            'DIAGNOSIS', 'DISPOSITION', 'EMERGENCY_DEPARTMENT',
              'EXAM', 'FAMILY_AND_SOCIAL_HISTORY',
                'GENERAL_HISTORY', 'GYNECOLOGICAL_HISTORY',
             'IMAGING', 'LABS', 'MEDICATIONS', 'OTHER_HISTORY',
               'PAST_MEDICAL_HISTORY', 'PAST_SURGICAL',
                 'PLAN', 'PROCEDURES', 'REVIEW_OF_SYSTEM','OTHER']
UNIMPORTANT_SECTIONS = [ 'GYNECOLOGICAL_HISTORY','EMERGENCY_DEPARTMENT','DISPOSITION','IMMUNIZATIONS','IMAGING','PROCEDURES','OTHER_HISTORY','LABS']
IMPORTANT_SECTIONS = [s for s in SECTIONS if s not in UNIMPORTANT_SECTIONS]
IMPORTANT_SECTION2BERT_ID = {IMPORTANT_SECTIONS[i]:i for i in range(len(IMPORTANT_SECTIONS))}
SECTION2BERT_ID = {SECTIONS[i]:i for i in range(len(SECTIONS))}